# Kickstart container config file - see https://nfra.infracamp.org
# Run kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"

packages: [php8.0-curl, php8.0-http, php8.0-raphf, php8.0-mbstring]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
  init:
    - "sudo mkdir -p $DATA_PATH"
    - "sudo chown -R www-data $DATA_PATH"
  test:
    - "curl http://localhost/hooks/startup"
    - "/opt/vendor/bin/ptest"

  dev:
    - "curl http://localhost/hooks/startup"

  run:
    - "curl http://localhost/hooks/startup"

